CREATE TABLE doctors (
   id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 100, INCREMENT BY 1) PRIMARY KEY,
   firstname VARCHAR (45),
   lastname VARCHAR (45),
   middle_name VARCHAR (45),
   specialization VARCHAR (45)
);

CREATE TABLE patients (
   id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 100, INCREMENT BY 1) PRIMARY KEY,
   firstname VARCHAR (45),
   lastname VARCHAR (45),
   middle_name VARCHAR (45),
   phone_number VARCHAR (45)
);

CREATE TABLE recipes (
   id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 100, INCREMENT BY 1) PRIMARY KEY,
   description VARCHAR (128),
   doctor INT,
   patient INT,
   creation_date DATETIME,
   validity DATETIME,
   priority INT,
   FOREIGN KEY (doctor) REFERENCES doctors (ID),
   FOREIGN KEY (patient) REFERENCES patients (ID)
);